[package]
name = "intent"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
ed25519-dalek = "2.1.1"
sha2 = "0.10"
hex = "0.4"
rand = "0.8"
base64 = "0.22.1"
axum = "0.7"
